services:
  app:
    restart: always
    build: .
    init: true
    ports:
      - "5000:5000"
  mongo:
    restart: always
    image: mongo:7.0-jammy
    volumes:
      - mongo-data-db:/data/db

volumes:
  mongo-data-db:
